on:
    push:
        tags:
            - "v*" # Push events to every tag not containing /
    workflow_dispatch:

name: Publish

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        permissions:
            contents: write
        env:
            CARGO_TERM_COLOR: always
        steps:
            - name: Checkout sources
              uses: actions/checkout@v2

            - name: Bump version
              uses: cute-lights/bump-version
              with:
                  version-prefix: "v"
                  push-to-branch: "main"
                  push-to-remote: "origin"
                  push-enabled: "true"
                  files: "package.json"
